"""Core data models for CapGuard."""

from typing import Dict, Any, Optional, List
from datetime import datetime
from pydantic import BaseModel, Field
import uuid


class CapabilityToken(BaseModel):
    """
    Token that specifies which tools an agent is allowed to use.
    
    This is the core security primitive - generated by the classifier
    based ONLY on the user's original request, before any external data.
    """
    
    request_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_request: str = Field(..., description="Original user request")
    granted_tools: Dict[str, bool] = Field(
        default_factory=dict,
        description="Map of tool_name -> granted (True/False)"
    )
    constraints: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Tool-specific constraints (e.g., email whitelist)"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Classifier confidence (0-1)"
    )
    classification_method: str = Field(
        default="unknown",
        description="Which classifier was used (rule-based, ml, llm)"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "abc-123",
                "user_request": "Summarize http://example.com",
                "granted_tools": {
                    "read_website": True,
                    "send_email": False,
                    "search_emails": False
                },
                "constraints": {},
                "confidence": 0.95,
                "classification_method": "rule-based"
            }
        }


class ToolParameter(BaseModel):
    """Definition of a tool parameter."""
    
    name: str
    type: str  # "str", "int", "float", "bool", etc.
    description: str
    required: bool = True
    default: Optional[Any] = None


class ToolDefinition(BaseModel):
    """
    Definition of a tool that agents can use.
    
    Includes metadata for security decisions (risk_level),
    user experience (description), and enforcement (parameters).
    """
    
    name: str = Field(..., description="Unique tool identifier")
    description: str = Field(..., description="What this tool does")
    parameters: List[ToolParameter] = Field(
        default_factory=list,
        description="Tool parameters"
    )
    risk_level: int = Field(
        ...,
        ge=1,
        le=5,
        description="Risk level: 1=safe (read-only), 5=critical (irreversible)"
    )
    requires_confirmation: bool = Field(
        default=False,
        description="Should user confirm before execution?"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "name": "send_email",
                "description": "Send an email message",
                "parameters": [
                    {"name": "to", "type": "str", "description": "Recipient", "required": True},
                    {"name": "subject", "type": "str", "description": "Subject", "required": True},
                    {"name": "body", "type": "str", "description": "Body", "required": True}
                ],
                "risk_level": 4,
                "requires_confirmation": True
            }
        }


class AuditLogEntry(BaseModel):
    """
    Audit log entry for tool execution attempts.
    
    Critical for security monitoring, compliance, and debugging.
    """
    
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    request_id: str
    tool_name: str
    action: str = Field(
        ...,
        description="Action taken: 'granted', 'blocked', 'executed', 'failed'"
    )
    capability_token: CapabilityToken
    parameters: Dict[str, Any] = Field(default_factory=dict)
    result: Optional[str] = None
    error: Optional[str] = None
    potential_attack: bool = Field(
        default=False,
        description="Flag for security team review"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "abc-123",
                "tool_name": "send_email",
                "action": "blocked",
                "capability_token": {"...": "..."},
                "parameters": {"to": "attacker@evil.com"},
                "potential_attack": True
            }
        }
